// Client-side resilient civic intelligence store for standalone Vercel demo mode

const potholeBefore = 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80';
const potholeAfter = 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80';
const garbageBefore = 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80';
const garbageAfter = 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80';
const streetlightBefore = 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80';
const streetlightAfter = 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80';
const waterBefore = 'https://images.unsplash.com/photo-1527525443983-6e60c75fff46?auto=format&fit=crop&w=800&q=80';
const drainBefore = 'https://images.unsplash.com/photo-1584467735815-f778f274e296?auto=format&fit=crop&w=800&q=80';

export const initialComplaints = [
  {
    _id: 'civic-1042',
    title: 'Huge Pothole Outside University Gate',
    description: 'There is a massive 2-foot deep pothole outside the college main gate. Vehicles and city buses are suddenly braking and swerving into oncoming traffic.',
    images: [potholeBefore],
    location: 'College Gate, North Blvd',
    coordinates: { lat: 12.9734, lng: 77.5962 },
    category: 'Road Infrastructure',
    department: 'Public Works',
    assignedDepartment: 'Public Works',
    severity: 'Critical',
    publicImpact: 'Severe',
    summary: 'Deep roadway fissure causing vehicular emergency braking and severe collision hazard near major educational institution.',
    keywords: ['pothole', 'college gate', 'braking', 'asphalt crater'],
    priorityScore: 94,
    priorityLevel: 'URGENT',
    impactFactors: { severity: 38, publicExposure: 24, reportFrequency: 19, locationImportance: 9, recency: 5 },
    status: 'IN_PROGRESS',
    reporterName: 'Alex Rivera',
    duplicateGroupId: { _id: 'cluster-1', title: 'Main Road Pothole Cluster', similarityScore: 89 },
    relatedReportsCount: 8,
    aiAnalysis: {
      detectedIssue: 'Road Pothole & Surface Collapse',
      confidence: 94,
      possibleRisk: 'High-speed vehicular damage, sudden braking collisions, severe hazard for two-wheelers',
      suggestedCategory: 'Road Infrastructure',
      suggestedDepartment: 'Public Works',
      isFallback: false,
      whyReasons: [
        'High severity crater (38/40) with depth exceeding 15cm',
        'Heavy commuter volume with 8 related reports clustered within 150m',
        'Prime location exposure directly adjacent to University transit gates',
        'Recency velocity: 5 reports in past 6 hours'
      ]
    },
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    _id: 'civic-1043',
    title: 'Asphalt Trench on 5th Main Avenue',
    description: 'Deep trench dug for underground utility pipe left open without barricades or asphalt patch.',
    images: [potholeBefore],
    location: '5th Main Avenue, Sector 2',
    coordinates: { lat: 12.9712, lng: 77.5990 },
    category: 'Road Infrastructure',
    department: 'Public Works',
    assignedDepartment: 'Public Works',
    severity: 'High',
    publicImpact: 'High',
    summary: 'Open utility trench across dual carriageway. Resurfaced and hot-mix sealed.',
    keywords: ['trench', 'asphalt', 'utility'],
    priorityScore: 84,
    priorityLevel: 'HIGH',
    impactFactors: { severity: 32, publicExposure: 20, reportFrequency: 14, locationImportance: 8, recency: 4 },
    status: 'RESOLVED',
    reporterName: 'Alex Rivera',
    relatedReportsCount: 3,
    resolutionProof: {
      image: potholeAfter,
      notes: 'Hot-mix bituminous asphalt patch applied by Public Works Unit #4. Level compaction verified.',
      resolvedByName: 'Sarah Jenkins',
      resolvedAt: new Date(Date.now() - 86400000).toISOString()
    },
    verificationSummary: {
      totalVotes: 4,
      resolvedVotes: 4,
      partialVotes: 0,
      unresolvedVotes: 0,
      status: 'CONFIRMED_RESOLVED'
    },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    _id: 'civic-1044',
    title: 'Pressurized Water Main Rupture on 4th Cross',
    description: 'Potable water main burst underground. High pressure water flooding the road and eroding sub-base pavement.',
    images: [waterBefore],
    location: '4th Cross, Industrial Layout',
    coordinates: { lat: 12.9652, lng: 77.6015 },
    category: 'Water Supply & Drainage',
    department: 'Water Supply & Sewerage Board',
    assignedDepartment: 'Water Supply & Sewerage Board',
    severity: 'High',
    publicImpact: 'Severe',
    summary: 'Underground high-pressure pipe breach eroding road foundation and causing clean water loss.',
    keywords: ['water burst', 'flooding', 'pipeline'],
    priorityScore: 89,
    priorityLevel: 'URGENT',
    impactFactors: { severity: 35, publicExposure: 22, reportFrequency: 18, locationImportance: 9, recency: 5 },
    status: 'ASSIGNED',
    reporterName: 'Alex Rivera',
    duplicateGroupId: { _id: 'cluster-3', title: 'Sector 4 Water Main Rupture', similarityScore: 95 },
    relatedReportsCount: 6,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    _id: 'civic-1045',
    title: 'Overflowing Waste Dump at Central Market',
    description: 'Multiple bins overflowing into pedestrian walkway for 4 days. Strong odor and stray animals obstructing entrance.',
    images: [garbageBefore],
    location: 'Commercial Market St, Gate 3',
    coordinates: { lat: 12.9785, lng: 77.5921 },
    category: 'Municipal Sanitation',
    department: 'Municipal Sanitation',
    assignedDepartment: 'Municipal Sanitation',
    severity: 'High',
    publicImpact: 'High',
    summary: 'Commercial zone garbage backlog spilling onto thoroughfare with biohazard risk.',
    keywords: ['garbage', 'dump', 'waste', 'market'],
    priorityScore: 82,
    priorityLevel: 'HIGH',
    impactFactors: { severity: 30, publicExposure: 21, reportFrequency: 17, locationImportance: 8, recency: 5 },
    status: 'IN_PROGRESS',
    reporterName: 'Priya Sharma',
    duplicateGroupId: { _id: 'cluster-2', title: 'Central Market Garbage Accumulation', similarityScore: 92 },
    relatedReportsCount: 5,
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    _id: 'civic-1046',
    title: 'Dark Stretch - 6 Broken Streetlights on Hospital Road',
    description: 'Complete blackout along 400m stretch outside Metro Childrens Hospital. Multiple broken fixtures and hanging cables.',
    images: [streetlightBefore],
    location: 'Hospital Link Road, West Gate',
    coordinates: { lat: 12.9690, lng: 77.5875 },
    category: 'Electrical & Lighting',
    department: 'Electrical & Lighting Authority',
    assignedDepartment: 'Electrical & Lighting Authority',
    severity: 'High',
    publicImpact: 'High',
    summary: 'Multi-pole blackout causing severe night-time visibility drop and safety hazards outside pediatric facility.',
    keywords: ['streetlight', 'dark', 'hospital'],
    priorityScore: 78,
    priorityLevel: 'HIGH',
    impactFactors: { severity: 32, publicExposure: 20, reportFrequency: 12, locationImportance: 10, recency: 4 },
    status: 'AWAITING_VERIFICATION',
    reporterName: 'Alex Rivera',
    relatedReportsCount: 4,
    resolutionProof: {
      image: streetlightAfter,
      notes: 'Installed high-output LED luminaires across poles #12 through #18. Wiring secured.',
      resolvedByName: 'Electrical Authority Tech Team',
      resolvedAt: new Date(Date.now() - 3600000 * 2).toISOString()
    },
    verificationSummary: {
      totalVotes: 1,
      resolvedVotes: 1,
      partialVotes: 0,
      unresolvedVotes: 0,
      status: 'PENDING'
    },
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    _id: 'civic-1047',
    title: 'Overflowing Storm Drain Flooding Ring Road Junction',
    description: 'Storm drain completely clogged with plastic and silt. Rainwater cannot escape, causing knee-deep waterlogging.',
    images: [drainBefore],
    location: 'Ring Road Junction, Near Flyover',
    coordinates: { lat: 12.9640, lng: 77.5920 },
    category: 'Water Supply & Drainage',
    department: 'Water Supply & Sewerage Board',
    assignedDepartment: 'Water Supply & Sewerage Board',
    severity: 'Critical',
    publicImpact: 'Severe',
    summary: 'Severe road junction inundation due to silt-choked drainage conduits.',
    keywords: ['drain', 'clogged', 'waterlogging', 'flooding'],
    priorityScore: 91,
    priorityLevel: 'URGENT',
    impactFactors: { severity: 36, publicExposure: 23, reportFrequency: 18, locationImportance: 9, recency: 5 },
    status: 'IN_PROGRESS',
    reporterName: 'Vikram Mehta',
    relatedReportsCount: 7,
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    _id: 'civic-1048',
    title: 'Illegal Debris Dumping in Residential Alley',
    description: 'Construction debris and domestic trash dumped illegally along the community park wall.',
    images: [garbageBefore],
    location: 'Park View Lane, Sector 3',
    coordinates: { lat: 12.9750, lng: 77.5890 },
    category: 'Municipal Sanitation',
    department: 'Municipal Sanitation',
    assignedDepartment: 'Municipal Sanitation',
    severity: 'Medium',
    publicImpact: 'Medium',
    summary: 'Illegal debris dumping cleared and sanitized with warning signage installed.',
    keywords: ['debris', 'dumping', 'park'],
    priorityScore: 68,
    priorityLevel: 'MEDIUM',
    impactFactors: { severity: 24, publicExposure: 18, reportFrequency: 12, locationImportance: 8, recency: 4 },
    status: 'RESOLVED',
    reporterName: 'Alex Rivera',
    resolutionProof: {
      image: garbageAfter,
      notes: 'Sanitation squad cleared 3 metric tons of debris. Disinfected perimeter.',
      resolvedByName: 'Municipal Sanitation Squad 7',
      resolvedAt: new Date(Date.now() - 86400000 * 4).toISOString()
    },
    verificationSummary: {
      totalVotes: 3,
      resolvedVotes: 3,
      partialVotes: 0,
      unresolvedVotes: 0,
      status: 'CONFIRMED_RESOLVED'
    },
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    _id: 'civic-1049',
    title: 'Malfunctioning Traffic Signal at South Circle',
    description: 'Traffic signals blinking erratically on all four approaches. Major crossway gridlock.',
    images: [],
    location: 'South Circle Intersection',
    coordinates: { lat: 12.9600, lng: 77.5980 },
    category: 'Traffic & Transport',
    department: 'Traffic Police & Transport Dept',
    assignedDepartment: 'Traffic Police & Transport Dept',
    severity: 'High',
    publicImpact: 'High',
    summary: 'Intersection signal synchronization failure resulting in quad-directional bottleneck.',
    keywords: ['signal', 'traffic', 'intersection'],
    priorityScore: 76,
    priorityLevel: 'HIGH',
    impactFactors: { severity: 28, publicExposure: 22, reportFrequency: 13, locationImportance: 8, recency: 5 },
    status: 'AI_CLASSIFIED',
    reporterName: 'Kavita Rao',
    relatedReportsCount: 3,
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
  }
];

export const initialAnalytics = {
  summary: {
    totalIssues: 14,
    activeIssues: 6,
    resolvedIssues: 8,
    highImpactIssues: 5,
    urgentIssues: 2,
    totalClusters: 3,
    resolutionRate: 57,
    avgResolutionTimeDays: 1.8,
    duplicateReductionPct: 42,
  },
  priorityQueue: initialComplaints.filter(c => c.status !== 'RESOLVED').slice(0, 5),
  trendAnalysis: {
    insights: [
      'Road-related reports increased +24% this week concentrated around College Gate and arterial corridors.',
      'Sanitation complaints remain stable with an average collection turnaround of 18 hours.',
      'Duplicate clustering reduced municipal dispatch overhead by 42%.',
      'Citizen ground-truth verification loop confirmed 94% true resolution accuracy.'
    ],
    trends: [
      { category: 'Road Infrastructure', trend: 'increasing', delta: '+24%', direction: 'up' },
      { category: 'Municipal Sanitation', trend: 'stable', delta: '+2%', direction: 'flat' },
      { category: 'Water Supply & Drainage', trend: 'increasing', delta: '+12%', direction: 'up' },
      { category: 'Electrical & Lighting', trend: 'decreasing', delta: '-8%', direction: 'down' },
    ]
  },
  departmentBreakdown: [
    { department: 'Public Works', count: 5 },
    { department: 'Municipal Sanitation', count: 3 },
    { department: 'Water Supply & Sewerage Board', count: 3 },
    { department: 'Electrical & Lighting Authority', count: 2 },
    { department: 'Traffic Police & Transport Dept', count: 1 },
  ]
};
